### ISSUE TITLE
"as is" option for partially filled cells

### ISSUE THREAD

**Issue by nncarlson** [laristra/portage#28]
For 1st order mapping it appears there is always some sort of tweak for partially filled cells after the raw intersection volume based mapping (CONSTANT, LOCALLY_CONSERVATIVE, and SHIFTED_CONSERVATIVE). I would find it useful to have an additional "AS_IS" option that just stopped at the raw mapping.

**Comment by raovgarimella** [comment]
Neil

Depending on what you want, AS_IS can mean CONSTANT or LOCALLY_CONSERVATIVE.

The ambiguity comes from whether you divide the integral quantity added into a target cell by the intersection volume (CONSTANT preserving) or by the target cell volume (LOCALLY_CONSERVATIVE).  Portage's default is CONSTANT preserving which means do no adjustments.

Rao



--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by nncarlson** [comment]
I may be confused about what `LOCALLY_CONSERVATIVE` implied.  I thought it also took stuff from a portion of a source cell that didn't intersect any target cell and added it to a nearby target cell (as opposed to `SHIFTED_CONSERVATIVE` which spreads it across the whole target).  Did I get that wrong?

**Comment by raovgarimella** [comment]
Neil


The LOCALLY_CONSERVATIVE option will not do anything about the portion of a source that is not covered by a target cell. Only SHIFTED_CONSERVATIVE (soon to be renamed GLOBAL_CONSERVATIVE) handles that.


Talking for the moment about densities and masses as it is easier, say I have the a source cell s with volume |s| and target cell t with volume |t| and the volume of intersection of s and t is |s^t| and the mass from the intersection is m = d_s*|s^t|. Then


d_t = m/|s^t|          -  CONSTANT PRESERVING

d_t = m/|t|              - LOCALLY CONSERVATIVE


Hope that clears things up.

Rao



--------------------------------------------------------------------
Rao V Garimella                              Tel: (505) 665-2928
T-5, MS B284                        '\   '\     FAX: (505) 665-5757
Los Alamos National Lab      ( )-( )  Email: rao@lanl.gov
Los Alamos, NM 87545                    Web: http://math.lanl.gov/~rao
--------------------------------------------------------------------

________________________________

**Comment by nncarlson** [comment]
Thanks for the clarification. I'm not sure how I came to my mistaken understanding of locally conservative.
