### ISSUE TITLE
Will a 2.2.0 release tarball be forthcoming?

### ISSUE THREAD

**Issue by nncarlson** [laristra/portage#30]
Will a full portage release tarball that corresponds to the v2.2.0 tag be forthcoming soon? One that contains all the dependencies (i.e. all the submodules). I'm looking to update the TPLs for Truchas to include portage and the usual git-archive stuff doesn't work because of your use of submodules. At this point I'm reduced to just tarring up a checkout of the v2.2.0 tag, including all the .git directories (if I exclude those there is a mysterious cmake failure with cinch).

Also you should note that the version info in `config/project.cmake` has not been updated to match the tag.

**Comment by cmsquared** [comment]
Yes, we need to do a better job of our release process, especially since we develop the code internally and only periodically release to GitHub.

For the tarball release: are you talking about one of the [GitHub created](https://github.com/laristra/portage/tags) releases?  Apparently GitHub doesn't have a way to enable included submodules for its auto-generated releases, but there is [interest](https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073/page/2).

**Comment by nncarlson** [comment]
That link is for the tag-based "releases", and yeah I found it doesn't include submodules. But there is a [separate tab](https://github.com/laristra/portage/releases) for releases.  Are those all auto-generated as well?  I thought those tarballs could be uploaded.

In any case, if you have something internally I can use let me know (nnc@lanl.gov).  Or if not perhaps we can discuss over email how I can make one that doesn't require the presence of the `.git` directories when running cmake.

**Comment by cmsquared** [comment]
The tarballs in that separate tab are in fact not auto-generated by GitHub.  You're right, we need to upload releases there ourselves and we should be better about that.  I will attempt to get all of our tagged versions to have tarballs there (with submodules) today.  One can use `git archive` to make such tarballs, but one needs an extra layer of scripting to recursively traverse the submodules.  I hope to add this as a target in our standard build process to do it for us when we want to cut a new release.  I will ping you when I have the tarballs updated.

Out of curiosity, what is your usecase for versioned tarballs as opposed to a git clone?  Are you storing the tarballs for a Truchas superbuild?

**Comment by cmsquared** [comment]
Please try the additional tarball for v2.2.0 [here](https://github.com/laristra/portage/releases).  GitHub still wants to create the "Source Code" zip and tarball, even though I have uploaded my own tarball that includes the submodules...

**Comment by nncarlson** [comment]
> Out of curiosity, what is your usecase for versioned tarballs as opposed to a git clone? Are you storing the tarballs for a Truchas superbuild?

Yes, for robustness (firewalls, no access to github.com, etc.)

> Please try the additional tarball for v2.2.0 here. 

Thanks for digging into this for me.  I tried it, but I'm still running into the same problem I had originally when I tarred up a clone without the `.git` subdirectories. There's something in the cmake configuration that is apparently trying to run git to poke at the local clone.  Here's my output from cmake
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/var/tmp/foo ..
-- The C compiler identification is Intel 18.0.5.20180823
-- The CXX compiler identification is Intel 18.0.5.20180823
-- Check for working C compiler: /opt/intel/compilers_and_libraries_2018.5.274/linux/bin/intel64/icc
-- Check for working C compiler: /opt/intel/compilers_and_libraries_2018.5.274/linux/bin/intel64/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2018.5.274/linux/bin/intel64/icpc
-- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2018.5.274/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Install prefix set to /var/tmp/foo
-- Found Git: /usr/bin/git (found version "2.9.5") 
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at cinch/cmake/cinch_minimum_required.cmake:31 (message):
  portage requries Cinch version 1.0 (found version )
Call Stack (most recent call first):
  config/project.cmake:9 (cinch_minimum_required)
  cinch/cmake/ProjectLists.txt:45 (include)
  CMakeLists.txt:40 (include)


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage_v2.2.0/build/CMakeFiles/CMakeOutput.log".
```

**Comment by cmsquared** [comment]
Ok, sorry for misunderstanding exactly your problem.  I'm on board now and understand.

The issue, as you pointed out, is buried within cinch in how it was designed to be used.  We are in the process of removing the dependency on cinch, but that will be for a future release (and should cut down on the size of the tarball).

There is a workaround, but I'm just checking now to make sure it works.

**Comment by cmsquared** [comment]
Ok, the workaround until we get cinch removed is to add a file called **.version** to *any* cinch directory (in this case `cinch` and `wonton/cinch`); this file just needs to have the string "1.0" in it.

I have updated the v2.2.0 tarball to have these files.

**Comment by nncarlson** [comment]
Works!  Thanks for taking the time to create the tarball for me -- greatly appreciated!
