### ISSUE TITLE
Need a full tarball of v2.2.3

### ISSUE THREAD

**Issue by nncarlson** [laristra/portage#33]
I would like to get a full tarball of the 2.2.3 release that includes all the submodules (and cinch workaround if still necessary).  I had the same request for 2.2.0; see issue #30 and its resolution.

**Comment by raovgarimella** [comment]
Neil
I made one here and tested it. Please check it out and let me know if it does not work

https://github.com/laristra/portage/releases/download/v2.2.3/portage_v2.2.3.tar.gz

**Comment by nncarlson** [comment]
I works. Thanks!
