### ISSUE TITLE
No need to set CMAKE_C_COMPILER to mpicc

### ISSUE THREAD

**Issue by junghans** [laristra/portage#8]
There is basically no need for `CMAKE_C_COMPILER=$(which mpicc)` (as suggested in the documentation) when CMake is calling `find_package(MPI)` (as we do).

Travis already builds portage this way with MPI. Plus, setting `CMAKE_C_COMPILER` might even lead to some strange build errors if the `mpicc` in your `PATH` differs from what CMake picks up with `find_package(MPI)`.

**Comment by cmsquared** [comment]
I vaguely remember CMake getting confused on some of our HPC machines when a module had been loaded.  Of course, I don't remember which machine/compiler combination, and I'm sure I probably can't reproduce it.  I'll try changing this internally and see what happens.

**Comment by junghans** [comment]
You could also make the argument the other way around (and I have seen that before), if the `mpicc` differs from the `libmpi` cmake picks up with `find_package(MPI)` it ends in a big mess.

**Comment by junghans** [comment]
This is broken again in v1.1.1 (found by spack)

**Comment by cmsquared** [comment]
I don't think it was ever fixed...  I forgot about trying to fix this.

Also, didn't realize we were in spack!

**Comment by cmsquared** [comment]
Testing this internally now...

**Comment by cmsquared** [comment]
First pass, removing this breaks every single one of our tests on our machines because it doesn't find the appropriate MPI methods.  I'll play with it some more to see if there is something missing in the include/link step with this...

**Comment by junghans** [comment]
Yeah, we in spack for a while (LLNL/spack#4029).

I think, there is a `target_link_libraries(${MPI_C_LIBRARIES})` missing somewhere.
